services:
  - type: web
    name: top-chef-backend
    runtime: node
    repo: https://github.com/Keln200/TOP-CHEF-EATERIES
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0